<?php

return [
    'disable' => env('CAPTCHA_DISABLE', false),
    'characters' => ['2', '3', '4', '5', '6', '7', '8', '9',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'm',
        'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'],
    'default' => [
        'length' => 4,
        'width' => 150,
        'height' => 42,
        'quality' => 90,
        'math' => false,
        'expire' => 120,
        'encrypt' => false,
    ],
    'flat' => [
        'length' => 4,
        'width' => 150,
        'height' => 42,
        'quality' => 100,
        'lines' => 2,
        'bgImage' => false,
        'bgColor' => '#f3f4f6',
        'fontColors' => ['#1e40af', '#4338ca', '#6d28d9', '#0e7490'],
        'contrast' => 0,
        'angle' => 8,
        'sharpen' => 5,
    ],
    'mini' => [
        'length' => 3,
        'width' => 60,
        'height' => 32,
    ],
    'inverse' => [
        'length' => 5,
        'width' => 120,
        'height' => 36,
        'quality' => 90,
        'sensitive' => true,
        'angle' => 12,
        'sharpen' => 10,
        'blur' => 2,
        'invert' => false,
        'contrast' => -5,
    ],
    'math' => [
        'length' => 9,
        'width' => 120,
        'height' => 36,
        'quality' => 90,
    ],
];
